### ISSUE TITLE
Atlas build error

### ISSUE THREAD

**Issue by chlebta** [layerhq/Atlas-iOS#1011]
Hello,
When I try to run the example project I get this issue : 

```
Undefined symbols for architecture armv7:
  "_LYRTypingIndicatorValueUserInfoKey", referenced from:
      -[ATLConversationViewController didReceiveTypingIndicator:] in ATLConversationViewController.o
  "_LYRMessageOptionsPushNotificationConfigurationKey", referenced from:
      -[ATLConversationViewController messageForMessageParts:MIMEType:pushText:] in ATLConversationViewController.o
  "_LYRConversationOptionsDeliveryReceiptsEnabledKey", referenced from:
      -[ATLConversationViewController conversationWithParticipants:] in ATLConversationViewController.o
  "_OBJC_CLASS_$_LYRConversation", referenced from:
      objc-class-ref in ATLConversationListViewController.o
      objc-class-ref in ATLConversationViewController.o
  "_LYRClientObjectChangesUserInfoKey", referenced from:
      -[ATLConversationViewController layerClientObjectsDidChange:] in ATLConversationViewController.o
  "_OBJC_CLASS_$_LYRCompoundPredicate", referenced from:
      objc-class-ref in ATLConversationViewController.o
  "_LYRConversationDidReceiveTypingIndicatorNotification", referenced from:
      -[ATLConversationViewController atl_registerForNotifications] in ATLConversationViewController.o
  "_OBJC_CLASS_$_LYRPushNotificationConfiguration", referenced from:
      objc-class-ref in ATLConversationViewController.o
  "_OBJC_CLASS_$_LYRQuery", referenced from:
      objc-class-ref in ATLConversationListViewController.o
      objc-class-ref in ATLConversationViewController.o
  "_OBJC_CLASS_$_LYRMessagePart", referenced from:
      objc-class-ref in ATLMessagingUtilities.o
  "_OBJC_CLASS_$_LYRPredicate", referenced from:
      objc-class-ref in ATLConversationListViewController.o
      objc-class-ref in ATLConversationViewController.o
  "_LYRTypingIndicatorParticipantUserInfoKey", referenced from:
      -[ATLConversationViewController didReceiveTypingIndicator:] in ATLConversationViewController.o
  "_LYRClientObjectsDidChangeNotification", referenced from:
      -[ATLConversationViewController atl_registerForNotifications] in ATLConversationViewController.o
  "_OBJC_CLASS_$_LYRMessage", referenced from:
      objc-class-ref in ATLConversationViewController.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by maju6406** [comment]
We made a small tweak to the LayerKit cocoapod. Can you try removing the Podfile.lock and Pods folder and try running 'pod install' again?

**Comment by nsantorello** [comment]
I have this same issue, tried removing Podfile.lock and rerunning `pod install` but still same error

**Comment by kmahal** [comment]
@nsantorello we just released a new Atlas version, let us know how it works.

**Comment by nsantorello** [comment]
I am using these versions:
```
  - Atlas (1.0.13):
    - LayerKit (>= 0.17.0)
```

Installs successfully but fails to build if I include `use_frameworks!` in my Podfile.  Builds successfully without `use_frameworks!`.

**Comment by kmahal** [comment]
@nsantorello Good to know, we'll note that.  Thanks!

**Comment by chlebta** [comment]
This solved my issue but now when I run my app it crash and I get this error : 
```
dyld: Library not loaded: @rpath/LayerKit.framework/LayerKit
  Referenced from: /var/mobile/Containers/Bundle/Application/21AF8E18-8286-48F7-95D2-B48F4F18BAE4/Storyboard.app/Storyboard
  Reason: image not found
```
normally it's related to **LayerKit (>= 0.17.0)**

**Comment by nishantdongare** [comment]
i tried everything mentioned above. But not able to solve it. Still facing the same issue.
platform :ios, '8.0'

use_frameworks!


inhibit_all_warnings!
pod 'Atlas', '< 1.0.14'
pod 'LayerKit', '>= 0.17.0'

My Pod file.
