### ISSUE TITLE
CocoaPods install doesn't work

### ISSUE THREAD

**Issue by nemo** [layerhq/Atlas-iOS#249]
Hey folks,

I'm getting this error when attempting to install the pod. Not sure if there's a way around this – do you have any suggestions?

``[!] The 'Pods' target has transitive dependencies that include static binaries: (/<path to project>/LayerKit.embeddedframework/LayerKit.framework)```

Cheers!

**Comment by kcoleman731** [comment]
Hi @nemo Can you tell me what version of Cocoapods you are using?

**Comment by nemo** [comment]
Hey, @kcoleman731 – I'm on `0.36.0.rc.1` (since I'm using Alamofire, it's a Swift based framework). Here's a copy of my Podfile:

```
platform :ios, '8.0'

pod 'Alamofire', '~> 1.1'
pod 'Taplytics'
pod 'MBProgressHUD'
pod 'Atlas'

use_frameworks!
```

**Comment by kcoleman731** [comment]
@nemo Looks like the `use_frameworks!` flag is going to be your issue. Why are you including?

**Comment by nemo** [comment]
@kcoleman731 I believe Alamofire's docs told me to throw it in there. But I believe it'll compile without – so I'm going to give that a try this weekend and see if it works :)

**Comment by nemo** [comment]
@kcoleman731 So it looks like because `Alamofire` is entirely in Swift, `use_frameworks!` is required for it to compile:

```[!] Pods written in Swift can only be integrated as frameworks; this feature is still in beta. Add `use_frameworks!` to your Podfile or target to opt into using it. ```

They've put out an article around this and how you can figure out ways around this [here](http://blog.cocoapods.org/Pod-Authors-Guide-to-CocoaPods-Frameworks/).

**Comment by kcoleman731** [comment]
@nemo Thanks for this. We are looking into this today and will sort it out.

**Comment by rlam3** [comment]
@nemo thank you!!!

**Comment by danieljacobarcher** [comment]
+1

**Comment by kcoleman731** [comment]
Hi All, Cocoapods 36.0 was released yesterday evening. We are migrating Atlas to support the new release today. Should be good to go after that. I'll throw a note on this thread when it is good to go. 

Thank you for your patience!

**Comment by danieljacobarcher** [comment]
@kcoleman731 Hey Kevin, still getting an error:
````[!] The 'Pods' target has transitive dependencies that include static binaries: (<path>/Pods/LayerKit/LayerKit.framework)````

**Comment by kcoleman731** [comment]
@danieljacobarcher This should have been resolved. Let me see what is going on. Thanks for the heads up.

**Comment by kcoleman731** [comment]
@danieljacobarcher Just fired up Atlas in a new Xcode project and everything is building just fine. Can you tell me what version of Cocoapods and XCode you are using?

@nemo Not sure if you saw but we released Atlas v 1.0.1 with support for cocoapods 0.36.0. Have you tried in stalling?

**Comment by danieljacobarcher** [comment]
@kcoleman731 It looks like it's tied to using the use_frameworks! flag in the Podfile. Installing Atlas via the newest Cocoapods works on its own, or with other obj-c pods, but swift pods and obj-c pods with use_frameworks! isn't working? Let me know if you have a solution! It seems like other pods have PRs for this fix as well.

**Comment by danieljacobarcher** [comment]
@kcoleman731 Here is my Podfile:

````
platform :ios, '8.0'
use_frameworks!

inhibit_all_warnings!

pod 'Atlas', '>= 1.0.1'

# Swift Pods
pod 'SwiftyJSON'
pod 'OAuthSwift'
````

And here's the result of `pod install`
````
Analyzing dependencies
Downloading dependencies
Using Atlas (1.0.1)
Using LayerKit (0.10.3)
Installing OAuthSwift (0.3.2)
Installing SwiftyJSON (2.1.3)
[!] The 'Pods' target has transitive dependencies that include static binaries: (<path>/Pods/LayerKit/LayerKit.framework)
````

**Comment by kcoleman731** [comment]
@danieljacobarcher Thank you for the info. I am now able to repro you issue. We are on it.

**Comment by danieljacobarcher** [comment]
@kcoleman731 Thank you.

**Comment by blakewatters** [comment]
It looks like this can be worked around by having the LayerKit podspec include a single source file in addition to the framework. I’ve got to retool the build process to make this happen, but should be able to push a refreshed podspec later today.

**Comment by cakper** [comment]
Hello guys, I'm struggling with exactly the same thing but on a different project. Could you guys point me how to fix this ```target has transitive dependencies that include static binaries``` problem?

Thanks, Kacper.

**Comment by blakewatters** [comment]
Hi @cakper -

What I’ve done to work around it is included a dummy file in the podspec for LayerKit. LayerKit is built as a framework and supports installation via CocoaPods via `vendored_frameworks`. Since there are not any source files, its linking path is different from typical source based pods and exposes this transitive dependency problem. My workaround was to add a single source file to the podspec that exports a single string constant symbol so that there’s a source file to compile and an object file to link.

**Comment by danieljacobarcher** [comment]
@blakewatters @kcoleman731 Awesome! No issues here now.

**Comment by blakewatters** [comment]
We’ve just pushed LayerKit v0.11.0 and Atlas v1.0.2 that includes the changes to deal with the transitive dependency linking fun. I’ve verified that installation with a Podfile like this works as expected:

```ruby
platform :ios, '8.0'
use_frameworks!

inhibit_all_warnings!

pod 'Atlas', '>= 1.0.2'

# Swift Pods
pod 'SwiftyJSON'
pod 'OAuthSwift'
```

**Comment by cakper** [comment]
@blakewatters thanks a lot for the details, that is helpful! :)

**Comment by blakewatters** [comment]
I actually had to unwind these changes — it just moved us from install problems to build problems. LayerKit is going to have to be distributed as a dynamic framework to solve these issues.

**Comment by andreicrisan** [comment]
Still facing issue when trying to include Atlas or LayerKit in my podfile.

 The 'Pods' target has transitive dependencies that include static binaries: (<path>/LayerKit/LayerKit.embeddedframework/LayerKit.framework). 

This is how my podfile looks like.

use_frameworks!


pod 'REFrostedViewController', '~> 2.4'
pod 'THCalendarDatePicker', '~> 1.0'
pod 'IDMPhotoBrowser', '~> 1.6'
pod 'SDWebImage', '~> 3.7'
pod 'Atlas', '>= 1.0.2'
pod 'Facebook-iOS-SDK', '~> 4.0'
pod 'SVProgressHUD', '~> 1.1'
pod 'MDCSwipeToChoose', '~> 0.2'
pod 'MWPhotoBrowser', '~> 1.4'

pod 'ILTranslucentView', '~> 0.1'
pod 'PSUpdateApp', '~> 2.0.5'

I have tried doing what @blakewatters  has suggested but did not manage to make it working. I've been struggling with this issue for more than a day now. Any suggestion will be just fine.

**Comment by AndrewSB** [comment]
I'm having the same problem. Here's my Podfile 

```
platform :ios, '8.0'
use_frameworks!
inhibit_all_warnings!

pod 'LayerKit'
pod 'Atlas', '>= 1.0.2'

pod 'FontAwesomeKit/IonIcons', '~> 2.2'
pod 'AFNetworking', '~> 2.5'
pod 'SVProgressHUD', '~> 1.1'
pod 'Cartography', '~> 0.5.0'
pod 'Toucan', '~> 0.2.0'
```

**Comment by ntnmrndn** [comment]
Same problem here with

`platform :ios, '8.0'
use_frameworks!
inhibit_all_warnings!

pod 'Alamofire'
pod 'JFBCrypt'
pod 'XCGLogger'
pod 'Atlas'`

I tried with the last production and pre release cocoapod version (pre2).

**Comment by ntnmrndn** [comment]
Our workaround was to perform a manual installation of Atlas (Layer still being installed by cocoapods).

**Comment by oferRounds** [comment]
@kcoleman731, any workaround for this issue? I'm also getting it (using the latest Layer and Atlas versions), when trying to inclde a swift pod (and adding use_frameworks!).
This is one that I'm adding: https://github.com/zhxnlai/ZLSwipeableViewSwift

**Comment by blakewatters** [comment]
I’m working on an update to the LayerKit build process to begin distributing dynamic frameworks. Unfortunately there are a number of annoying sticking points with some of our dependencies and its been slow going. I expect to have it straightened out in a few days.

**Comment by oferRounds** [comment]
Yes, I understand... Anyhow, thanks, that would be great :)

**Comment by ads1018** [comment]
+1

**Comment by stefangeir** [comment]
+1

**Comment by mattmcneeney** [comment]
+1

**Comment by cshah3** [comment]
+1

**Comment by mchu4545** [comment]
+1

**Comment by blin89** [comment]
+1

**Comment by SaagarGodithi** [comment]
+1

**Comment by gvmatera** [comment]
+1

**Comment by WANGjieJacques** [comment]
+1

**Comment by vinzen** [comment]
+1

**Comment by gvmatera** [comment]
Can you give an update on when a fix for this will be available?

**Comment by blakewatters** [comment]
We are now building LayerKit into a dynamic framework. The next release will solve these packaging issues

**Comment by gvmatera** [comment]
Great! Do you know when this will be available? (Even just a rough idea.)

**Comment by chenyuan** [comment]
+1

**Comment by jhau** [comment]
+1

**Comment by blakewatters** [comment]
We are still working on it. Hopefully next week we can ship the update

**Comment by oferRounds** [comment]
:+1:

**Comment by ippy04** [comment]
+1

**Comment by nikriek** [comment]
+1

**Comment by rishabhtayal** [comment]
+1

**Comment by nratter** [comment]
any timeframe for the update?

**Comment by nsantorello** [comment]
+1

**Comment by oferRounds** [comment]
:+1:

**Comment by SK0RM** [comment]
:+1:

**Comment by nosrak113** [comment]
+1

**Comment by ippy04** [comment]
:+1:

**Comment by dfinzer** [comment]
+1

**Comment by vikmeup** [comment]
Do you know when this will be available?

**Comment by vikmeup** [comment]
@blakewatters, @chipxsd, @kmahal could you guys give us some estimates? I can't move forward until Atlas framework will be fixed. Thanks.

**Comment by sysadminPSQ** [comment]
@blakewatters @kcoleman731 Is there any time frame we can expect as to when this issue will be fixed? Our entire work is dependent on the update to  support use_frameworks! tag in cocoapods.

**Comment by chenyuan** [comment]
i'm currently using cocoapods to integrate Layer, and drag&drop Atlas source code in my project. anyone who got stuck, you may want to try this as a temporary workaround.

**Comment by medjessy** [comment]
+2

**Comment by devilbags** [comment]
For anyone who are still having this same problem. I used @chenyuan method to work around the issue and it worked fine

**Comment by mgerdt** [comment]
any news on fixing the issue?

**Comment by blakewatters** [comment]
Fixed. Atlas v1.0.12 has a dependency on LayerKit v0.17.0 which is distributed as a dynamic framework.

**Comment by chenyuan** [comment]
tried to integrate with cocoapods, received similar error described here: http://stackoverflow.com/questions/32668723/atladdressbarviewcontroller-h-not-found-in-atlas-h

xcode 7 swift project. even tested in a brand new project, same issue

**Comment by mgerdt** [comment]
Same here. Cocoapods 0.39
anything I might have missed?

**Comment by chenyuan** [comment]
@mgerdt yup, pod install has no issues, compiling does.

**Comment by mgerdt** [comment]
Still can't install via cocoapods. Any hints?

**Comment by damirstuhec** [comment]
Same here. The error is still `The 'Pods' target has transitive dependencies`.

**Comment by bradytate** [comment]
I was previously getting the same error.

Try including the following lines at the top of your Podfile: 
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '8.0'

Because of dynamic frameworks, Layer no longer supports pre-iOS 8 so you also need to set your minimum target as 8.0. https://developer.layer.com/docs/ios/changelog

**Comment by mgerdt** [comment]
Thanks, but that is already in my podfile. Still no luck.

**Comment by hnchan** [comment]
I am also facing this problem.
The 'Pods' target has transitive dependencies....

**Comment by chapayGhub** [comment]
I changed my pod file
platform :ios, '8.0'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

pod 'Atlas'
pod 'LYRCountDownLatch'
pod 'LayerKit'
pod 'SVProgressHUD'
pod 'ClusterPrePermissions', '~> 0.1'

remove Podfile.lock and Atlas Messenger.xcworkspace
then run pod install

**Comment by mgerdt** [comment]
Still 'The 'Pods' target has transitive dependencies that include static binaries: (...../Pods/LayerKit/LayerKit.framework)' ...

**Comment by brandy2015** [comment]
I solve it as chapayGhub commented on 15 Oct 2015

platform :ios, '8.0'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

pod 'Atlas'
pod 'LYRCountDownLatch'
pod 'LayerKit'
pod 'SVProgressHUD'
pod 'ClusterPrePermissions', '~> 0.1'

remove Podfile.lock and Atlas Messenger.xcworkspace
then run pod install



and  removing Podfile.lock and Pods is  important ,ten  rebuild it by running pod install

**Comment by KarenGit** [comment]
Hi everyone
I have problem with Atlas framework.
In bridge header file. #import 'Atlas.h' file not found

This is my pod file 

target 'MyApp' do
use_frameworks!
pod ‘Parse’
pod 'ParseFacebookUtilsV4'
pod 'ParseUI'
pod ’FBSDKCoreKit’
pod 'FBSDKLoginKit’
pod 'FBSDKShareKit'
pod 'JWGCircleCounter' 
pod 'UIImage-Helpers'
pod 'FontAwesomeKit'
pod 'SDWebImage', '~>3.7'
pod 'CWStatusBarNotification', '~> 2.3.3'
pod 'NSDate+TimeAgo'
pod 'DLRadioButton'
pod 'DateTools'
pod 'SVProgressHUD'
pod 'JSQMessagesViewController'
pod 'SVProgressHUD'

pod 'LayerKit'
pod 'Atlas'

pod 'JTSImageViewController'
pod 'EECircularMusicPlayerControl'
pod 'DGActivityIndicatorView'
pod 'PARTagPicker'
pod 'DZNPhotoPickerController'
pod "FacebookImagePicker"
pod 'BEMCheckBox'
pod 'FlickrKit'
pod ‘AFNetworking’

end
